services:
  jobmanager:
    build:
      context: .
    container_name: flink-jobmanager
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        state.backend.type: rocksdb
        state.checkpoints.dir: s3://warehouse/checkpoints
        state.savepoints.dir: s3://warehouse/savepoints
        s3.endpoint: http://192.168.1.4:3900
        s3.path-style-access: true
        s3.multiobjectdelete.enable: false
        s3.entropy.enabled: true
        s3.access-key: GK52146e50e9e1136a72bdfb00
        s3.secret-key: 8700753fa07f62ff464697ff58edff635c7e0ccfd3a60127c882fa6bebcdfbcf
    ports:
      - "8081:8081"
    volumes:
      - ./data/flink:/opt/flink/data
      - ./sql:/opt/flink/sql

  taskmanager:
    build:
      context: .
    container_name: flink-taskmanager
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        taskmanager.memory.process.size: 2g
        state.backend.type: rocksdb
        s3.endpoint: http://192.168.1.4:3900
        s3.path-style-access: true
        s3.multiobjectdelete.enable: false
        s3.entropy.enabled: true
        s3.access-key: GK52146e50e9e1136a72bdfb00
        s3.secret-key: 8700753fa07f62ff464697ff58edff635c7e0ccfd3a60127c882fa6bebcdfbcf
    volumes:
      - ./data/flink:/opt/flink/data
      - ./sql:/opt/flink/sql
    depends_on:
      - jobmanager
    deploy:
      replicas: 4

  sql-client:
    build:
      context: .
    container_name: flink-sql-client
    command: >
      bash -c "
        sleep 30 &&
        /opt/flink/bin/sql-client.sh
      "
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        s3.endpoint: http://192.168.1.4:3900
        s3.path-style-access: true
        s3.multiobjectdelete.enable: false
        s3.entropy.enabled: true
        s3.access-key: GK52146e50e9e1136a72bdfb00
        s3.secret-key: 8700753fa07f62ff464697ff58edff635c7e0ccfd3a60127c882fa6bebcdfbcf
    volumes:
      - ./sql:/opt/flink/sql
    depends_on:
      - jobmanager
      - taskmanager
    stdin_open: true
    tty: true
